name: Change Text in Code

on:
  push:
    branches:
      - hydro

jobs:
  change_text:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Replace text
      run: |
        find . -type f -name '*.py' -exec sed -i 's#pyrogram#hydrogram#g' {} +

    - name: Commit changes
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add .
        git commit -m "Replace 'ubot.on_message(anjay(' with 'KY.UBOT('"
        git push
